// data.jsx — DALIZA catalog data
// Placeholder imagery: striped SVG with monospace label until real photos are uploaded.

const D_PALETTE = {
  ivory:    '#f5f0e6',
  bone:     '#ebe2d3',
  sand:     '#d9c9a9',
  taupe:    '#a08d6e',
  clay:     '#7a5d3f',
  ink:      '#1a1614',
  ink60:    'rgba(26,22,20,0.62)',
  ink40:    'rgba(26,22,20,0.40)',
  ink20:    'rgba(26,22,20,0.18)',
  ink08:    'rgba(26,22,20,0.08)',
  // dark mode counterparts
  d_bg:     '#15120f',
  d_card:   '#1f1c18',
  d_text:   '#f0eadd',
  d_text60: 'rgba(240,234,221,0.62)',
  d_text20: 'rgba(240,234,221,0.18)',
};

// product palette tones (used as visual placeholder fills)
const TONE = {
  ivory:    { bg: '#efe9dc', stripe: '#e3dccd' },
  bone:     { bg: '#e2d8c5', stripe: '#d5cab4' },
  oat:      { bg: '#cdbfa3', stripe: '#bfb094' },
  taupe:    { bg: '#9d8a6f', stripe: '#8c7a60' },
  cocoa:    { bg: '#5a4633', stripe: '#4d3b2b' },
  black:    { bg: '#1a1614', stripe: '#2a2420' },
  navy:     { bg: '#222a36', stripe: '#1a212c' },
  olive:    { bg: '#5a5b3e', stripe: '#4a4b32' },
  rust:     { bg: '#9a5a3c', stripe: '#874e34' },
  ecru:     { bg: '#d8cdb6', stripe: '#cbbfa4' },
};

const CATEGORIES = [
  { id: 'all',     name: 'Todo' },
  { id: 'knit',    name: 'Punto' },
  { id: 'shirts',  name: 'Camisería' },
  { id: 'tailor',  name: 'Sastrería' },
  { id: 'denim',   name: 'Denim' },
  { id: 'dresses', name: 'Vestidos' },
  { id: 'outer',   name: 'Abrigos' },
];

const PRODUCTS = [
  {
    id: 'p01',
    name: 'Camisa lino Adriá',
    category: 'shirts',
    price: 145,
    label: 'CAMISA · LINO',
    tones: ['ivory', 'bone', 'black'],
    sizes: ['XS', 'S', 'M', 'L'],
    fabric: '100% lino europeo',
    care: 'Lavado en frío. Secar a la sombra.',
    origin: 'Confeccionado en Portugal',
    description: 'Camisa de lino con caída fluida y costura francesa. Cuello cubano relajado, puños de un solo botón.',
    look: 'LOOK 02',
    badge: null,
    new: true,
  },
  {
    id: 'p02',
    name: 'Pantalón sastre Marta',
    category: 'tailor',
    price: 220,
    label: 'PANTALÓN · LANA',
    tones: ['black', 'cocoa', 'taupe'],
    sizes: ['34', '36', '38', '40', '42'],
    fabric: 'Lana fría italiana 240g',
    care: 'Limpieza en seco recomendada.',
    origin: 'Confeccionado en España',
    description: 'Pantalón de pinza con caída clásica. Cintura alta, talle recto y vuelta cosida a mano.',
    look: 'LOOK 04',
    badge: null,
  },
  {
    id: 'p03',
    name: 'Jersey cashmere Olea',
    category: 'knit',
    price: 295,
    label: 'JERSEY · CASHMERE',
    tones: ['ecru', 'oat', 'cocoa'],
    sizes: ['XS', 'S', 'M', 'L'],
    fabric: '100% cashmere mongol',
    care: 'Lavar a mano con jabón neutro.',
    origin: 'Tejido en Italia',
    description: 'Jersey de cuello redondo en punto fino de dos cabos. Ribete de canalé suave.',
    look: 'LOOK 01',
    badge: 'ESENCIAL',
  },
  {
    id: 'p04',
    name: 'Abrigo lana Caterina',
    category: 'outer',
    price: 620,
    label: 'ABRIGO · LANA',
    tones: ['cocoa', 'black', 'oat'],
    sizes: ['S', 'M', 'L'],
    fabric: '90% lana virgen, 10% cashmere',
    care: 'Limpieza en seco.',
    origin: 'Confeccionado en Italia',
    description: 'Abrigo cruzado con hombros estructurados y cinturón de la misma tela. Forro de viscosa.',
    look: 'LOOK 06',
    badge: null,
  },
  {
    id: 'p05',
    name: 'Vestido seda Ines',
    category: 'dresses',
    price: 340,
    label: 'VESTIDO · SEDA',
    tones: ['ivory', 'black', 'rust'],
    sizes: ['XS', 'S', 'M', 'L'],
    fabric: '100% seda lavable',
    care: 'Lavado en frío en bolsa de malla.',
    origin: 'Confeccionado en Italia',
    description: 'Vestido midi de tirantes con escote en pico y caída en bies.',
    look: 'LOOK 03',
    badge: null,
    new: true,
  },
  {
    id: 'p06',
    name: 'Jeans rectos Hera',
    category: 'denim',
    price: 165,
    label: 'JEAN · DENIM',
    tones: ['ecru', 'navy', 'black'],
    sizes: ['24','25','26','27','28','29','30'],
    fabric: 'Denim japonés 13.5oz',
    care: 'Lavar del revés en frío.',
    origin: 'Tejido en Japón, confeccionado en Portugal',
    description: 'Jeans de tiro alto y pierna recta. Costura selvedge y rivets de cobre.',
    look: 'LOOK 05',
    badge: null,
  },
  {
    id: 'p07',
    name: 'Camiseta algodón Selma',
    category: 'shirts',
    price: 75,
    label: 'CAMISETA · ALGODÓN',
    tones: ['ivory', 'black', 'oat'],
    sizes: ['XS', 'S', 'M', 'L'],
    fabric: 'Algodón pima peruano',
    care: 'Lavar en frío.',
    origin: 'Confeccionado en Portugal',
    description: 'Camiseta de manga corta con corte recto y cuello reforzado.',
    look: null,
    badge: 'ESENCIAL',
  },
  {
    id: 'p08',
    name: 'Falda lápiz Beatriz',
    category: 'tailor',
    price: 195,
    label: 'FALDA · LANA',
    tones: ['black', 'cocoa'],
    sizes: ['XS', 'S', 'M', 'L'],
    fabric: 'Lana virgen 280g',
    care: 'Limpieza en seco.',
    origin: 'Confeccionado en España',
    description: 'Falda lápiz por la rodilla con abertura trasera y forro de cupro.',
    look: 'LOOK 04',
    badge: null,
  },
  {
    id: 'p09',
    name: 'Cárdigan punto Lia',
    category: 'knit',
    price: 245,
    label: 'CÁRDIGAN · MERINO',
    tones: ['oat', 'olive', 'black'],
    sizes: ['XS', 'S', 'M', 'L'],
    fabric: '100% lana merino',
    care: 'Lavar a mano.',
    origin: 'Tejido en Italia',
    description: 'Cárdigan de cuello en V con botones de nácar. Punto canalé fino.',
    look: 'LOOK 01',
    badge: null,
  },
  {
    id: 'p10',
    name: 'Trench gabardina Vera',
    category: 'outer',
    price: 540,
    label: 'TRENCH · GABARDINA',
    tones: ['ecru', 'oat'],
    sizes: ['S', 'M', 'L'],
    fabric: 'Gabardina de algodón impermeable',
    care: 'Limpieza en seco.',
    origin: 'Confeccionado en Italia',
    description: 'Trench clásico con doble botonadura, cinturón y canesú trasero.',
    look: 'LOOK 06',
    badge: null,
  },
  {
    id: 'p11',
    name: 'Vestido punto Aria',
    category: 'dresses',
    price: 285,
    label: 'VESTIDO · PUNTO',
    tones: ['ivory', 'black', 'taupe'],
    sizes: ['XS','S','M','L'],
    fabric: 'Mezcla lana–seda',
    care: 'Lavar a mano.',
    origin: 'Tejido en Italia',
    description: 'Vestido midi de manga larga en punto fino. Cuello redondo y caída fluida.',
    look: 'LOOK 03',
    badge: null,
  },
  {
    id: 'p12',
    name: 'Jeans wide Pomelo',
    category: 'denim',
    price: 175,
    label: 'JEAN · WIDE',
    tones: ['ecru', 'navy'],
    sizes: ['24','25','26','27','28','29','30'],
    fabric: 'Denim japonés 12oz',
    care: 'Lavar del revés en frío.',
    origin: 'Tejido en Japón',
    description: 'Jean de pierna ancha y tiro alto. Bolsillos delanteros oblicuos.',
    look: 'LOOK 05',
    badge: null,
    new: true,
  },
];

const LOOKS = [
  { id: 'LOOK 01', title: 'Mañanas de lana',     subtitle: 'Punto y tonos arena',     items: ['p03','p06','p09'] },
  { id: 'LOOK 02', title: 'Lino al sol',          subtitle: 'Camisería ligera',        items: ['p01','p12','p07'] },
  { id: 'LOOK 03', title: 'Vestidos de tarde',    subtitle: 'Seda y punto',            items: ['p05','p11','p09'] },
  { id: 'LOOK 04', title: 'Sastrería suave',      subtitle: 'Pantalón y falda',        items: ['p02','p08','p07'] },
  { id: 'LOOK 05', title: 'Denim selvedge',       subtitle: 'Japón crudo',             items: ['p06','p12','p07'] },
  { id: 'LOOK 06', title: 'Capas de invierno',    subtitle: 'Abrigo y trench',         items: ['p04','p10','p03'] },
];

Object.assign(window, { D_PALETTE, TONE, CATEGORIES, PRODUCTS, LOOKS });
